name: Shadow_Ultimate_System
on:
  workflow_dispatch:

jobs:
  honeygain:
    runs-on: ubuntu-latest
    steps:
      - name: Launch Dual Nodes
        run: |
          docker run -d honeygain/honeygain -tou-accept -email ${{ secrets.MAIL1 }} -pass ${{ secrets.PASS1 }} -device "Cloud_Alpha"
          docker run -d honeygain/honeygain -tou-accept -email ${{ secrets.MAIL2 }} -pass ${{ secrets.PASS2 }} -device "Cloud_Beta"
          echo "Sir, both nodes are active. System will run for 6 hours."
          sleep 21600
